name: Deploy to PTServidor

on:
  push:
    branches:
      - main
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy to PTServidor
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: sintonizamais.pt
        username: sintoniz
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/
